#!/bin/bash
# Aothor: Enver Önder USLU
# Date: 21.06.2025
# Description: This script demonstrates the use of if statements in bash.

echo "Enter a number greatef then 10:"
read number

if [ $number -gt 10 ]; then
    echo "The number is greater than 10. Aferin"
else
    echo "Beyinsiz. The number is not greater then 10."
fi
