---

  - hosts: all
    become: true
    tasks:
    
    - name: updates apt packet index
      ansible.builtin.package:
        name:
         - apache2
         - libapache2-mod-php  
        state: latest    
        update_cache: yes
